Draft section on making a PR
ProjectPythia/pythia-foundations pull request #210
Opened 2022-01-14 23:56 UTC by clyne

Contributes "Opening a Pull Request on GitHub" section to #99

2022-01-14 23:59 UTC, clyne commented
@r-ford just tagging you on this PR because it looks like you are assigned to "Contribute to Project Pythia via GitHub". There is definitely some overlap :-). Feel free to review/suggest as well.

2022-01-24 18:32 UTC, clyne commented
@ktyle , @brian-rose , @dcamron just checking in. Hoping to get this PR merged by wednesday for the EC hackathon. Please just let me know if you're clogged up and I should try to reassign. Thanks!

2022-01-24 18:38 UTC, dcamron commented
I'll be able to review tomorrow!

2022-01-24 21:19 UTC, brian-rose commented
I'll get a review done tonight or tomorrow.

2022-01-25 00:49 UTC, brian-rose reviewed
Ok @clyne I've gone through with my fine-toothed comb! Lots of small suggestions and comments throughout.

At the macro level, I have four main comments:
1. Congratulations on taking this on! It's a daunting subject and this is a great contribution to Foundations.
2. There's some pretty dense text here! The more we can break it up visually with paragraph breaks and callouts, the more approachable it may be. I added several specific suggestions along these lines.
2. If we want to shorten this section and target "contributing to Pythia" as an explicit learning goal, we could actually remove all mention of the "Feature branch workflow" and focus exclusively on the "Forking workflow". In my experience the Forking workflow rules the roost even for collaborators with write-access to the upstream repository (e.g., we the core Pythia team use it on our own repos). I think your text gives a really good orientation to these different workflows. And there is some pedogogical sense to starting with the simpler workflow. But there's also the real possibility of cognitive overload to the learner who craves explicit instructions for how to get started on a real project. Given the short time frame we're working with here, we could consider deferring debate on this to a future revision cycle. I'm fine with that.
3. There is definitely some repetition and/or inconsistency between this material and @jukent's "Git branches" material in #207. Again we may need to postpone efforts to synchronize all this content until the macro-review called for in #214. But we could offer some more explicit instructions toward the end of the "Forking workflow" section for opening an actual PR on the sandbox repo. That would build more explicitly on our earlier sections.

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +navigating to your repo do the following:
This sentence could be removed (repetitive)

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +1. Under “Compare changes”, make sure that `base` is set to main, and `compare` is set to the name of your feature branch, “my-new-feature”
```suggestion
1. Under “Compare changes”, make sure that `base` is set to `main`, and `compare` is set to the name of your feature branch, `my-new-feature`
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +1. Click on “Pull requests” in the top navigation bar
One or more screenshots would be a nice touch here. But this could also wait for a future revision.

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +starting on a new feature, or if the main branch on remote may have
```suggestion
starting on a new feature, or if the `main` branch on remote may have
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +been updated while you were working on my-new-feature, it is a good
```suggestion
been updated while you were working on `my-new-feature`, it is a good
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +idea to periodically sync up with the remote main. Make sure all
```suggestion
idea to periodically sync up with the remote `main`. Make sure all
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +of your changes to my-new-branch have been committed to the local
```suggestion
of your changes to `my-new-feature` have been committed to the local
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git commit -m "having fun yet?" .
```suggestion
git commit -m "having fun yet?" .
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git clone repository-url local-directory-name
Here and elsewhere, I suggest removing the leading `$ ` so that the user can directly copy and paste commands into their terminal. JupyterBook actually provides a handy "copy" button on every code block. The `$ ` will break this functionality.

(Unfortunately we haven't been very consistent about this in Foundations)

```suggestion
git clone repository-url local-directory-name
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git clone https://github.com/ProjectPythia/github-sandbox.git
```suggestion
git clone https://github.com/ProjectPythia/github-sandbox.git
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git push --set-upstream origin my-new-feature
```suggestion
git push --set-upstream origin my-new-feature
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git push
```suggestion
git push
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git merge main
```suggestion
git checkout main
git pull
git checkout my-new-feature
git merge main
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git checkout -b my-new-feature
```suggestion
git checkout -b my-new-feature
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git pull
```suggestion
cd github-sandbox
git checkout main
git pull
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +1. The developer submits a PR via GitHub to the upstream repository
Again here I prefer the term "contributor" over "developer"
```suggestion
1. A contributor _forks_ the upstream repository, creating a remote clone that is owned by the contributor: the personal repository
1. The contributor then clones the newly created personal remote repository, creating a local copy. Yup, that is two clones.
1. The contributor creates a new branch in their local repository
1. The contributor makes changes to the branch and commits them to their local repository
1. The contributor pushes the branch to their personal remote repository that was created in step 1
1. The contributor submits a PR via GitHub to the upstream repository
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +commit your changes, and push the commits to your personal repository.
```suggestion
commit your changes, and push the new branch with your commits to your personal repository.
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +1. Under “Compare changes”, make sure that `base` is set to main, and `compare` is set to the name of your feature branch, “my-new-feature”
```suggestion
1. Under “Compare changes”, make sure that `base` is set to `main`, and `compare` is set to the name of your feature branch, `my-new-feature`
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +been updated while you were working on my-new-feature, it is a good
```suggestion
been updated while you were working on `my-new-feature`, it is a good
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +idea to periodically sync up with the remote main. When working
```suggestion
idea to periodically sync up with the remote `main`. When working
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git remote -v
```suggestion
git remote -v
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +Where upstream-url is the URL of the upstream repository.
```suggestion
Where `upstream-url` is the URL of the upstream repository.
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +- Making a PR on GitHub is pretty simple. The steps that lead up to
I'm leery of the "pretty simple" statement here, given how much text we've just asked the reader to sift through! Maybe just omit this first sentence.

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +  project that for which they do not have write access to the repository.
```suggestion
  project for which they do not have write access to the repository.
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git remote add upstream upstream-url
```suggestion
git remote add upstream upstream-url
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +$ git merge upstream/main
```suggestion
git fetch upstream
git checkout main
git merge upstream/main
```

2022-01-25 00:49 UTC, brian-rose commented on foundations/github/github-pull-request.md
> +1. The developer submits a PR via GitHub
I may be picking nits here, but I prefer the word "contributor" over "developer". Partly for consistency with the paragraph above, but also because the vast majority of our target audience will *not* self-identify as "developer".
```suggestion
1. A contributor clones a personal remote repository, creating a local copy
1. The contributor creates a new branch in their local repository
1. The contributor makes changes to the branch and commits them to
   their local repository
1. The contributor _pushes_ the branch to a remote repository
1. The contributor submits a PR via GitHub
```

2022-01-25 02:22 UTC, clyne commented on foundations/github/github-pull-request.md
Done.

2022-01-25 02:23 UTC, clyne commented on foundations/github/github-pull-request.md
>  - **Time to learn**: 30 minutes
I agree. Changed to 60.

2022-01-25 02:23 UTC, clyne commented on foundations/github/github-pull-request.md
> +become part of the destination repo. Just like issues, PRs have
Done.

2022-01-25 02:25 UTC, clyne commented on foundations/github/github-pull-request.md
> +that the maintainers of another destination repository pull a git
Changed. Consistency is an area we may want to look at across all of the GitHub content.

2022-01-25 02:28 UTC, clyne commented on foundations/github/github-pull-request.md
> +recipes, are referred to as _workflows_. The sequence of steps
done

2022-01-25 02:31 UTC, clyne commented on foundations/github/github-pull-request.md
> +Requests for two commonly used workflows: The Git Feature Branch
done

2022-01-25 02:57 UTC, clyne commented on foundations/github/github-pull-request.md
> +the new branch is pushed to the remote repository. At this point,
done

2022-01-25 02:58 UTC, clyne commented on foundations/github/github-pull-request.md
> +Don't forget that trailing "." or `git commit` will fail. That's one of the
done.

2022-01-25 03:00 UTC, clyne commented on foundations/github/github-pull-request.md
> +navigating to your repo do the following:
done.

2022-01-25 03:01 UTC, clyne commented on foundations/github/github-pull-request.md
> +- Making a PR on GitHub is pretty simple. The steps that lead up to
done.

2022-01-25 03:06 UTC, clyne commented
> Ok @clyne I've gone through with my fine-toothed comb! Lots of small suggestions and comments throughout.
> 
> At the macro level, I have four main comments:
> 
> 1. Congratulations on taking this on! It's a daunting subject and this is a great contribution to Foundations.

Definitely more here than I was planning!

> 2. There's some pretty dense text here! The more we can break it up visually with paragraph breaks and callouts, the more approachable it may be. I added several specific suggestions along these lines.
> 3. If we want to shorten this section and target "contributing to Pythia" as an explicit learning goal, we could actually remove all mention of the "Feature branch workflow" and focus exclusively on the "Forking workflow". In my experience the Forking workflow rules the roost even for collaborators with write-access to the upstream repository (e.g., we the core Pythia team use it on our own repos). I think your text gives a really good orientation to these different workflows. And there is some pedogogical sense to starting with the simpler workflow. But there's also the real possibility of cognitive overload to the learner who craves explicit instructions for how to get started on a real project. Given the short time frame we're working with here, we could consider deferring debate on this to a future revision cycle. I'm fine with that.

These are valid points. Agreed, that Forking Workflow works in all cases. However, the extra complexity around keeping things synced drove me to discuss the much simpler alternative. We can revisit this.

> 4. There is definitely some repetition and/or inconsistency between this material and @jukent's "Git branches" material in #207. Again we may need to postpone efforts to synchronize all this content until the macro-review called for in #214. But we could offer some more explicit instructions toward the end of the "Forking workflow" section for opening an actual PR on the sandbox repo. That would build more explicitly on our earlier sections.

Let's revisit when we do a top-to-bottom review.

Thanks for your detailed comments, @brian-rose !

2022-01-25 13:59 UTC, brian-rose commented
Closing and reopening to try to get the preview action to complete.

2022-01-25 14:31 UTC, brian-rose approved these changes
Ready to ship!

2022-01-26 03:01 UTC, dcamron requested changes
So I've reviewed so far basically just for small things. Looks great, and I **really** appreciate the introductory section and the "code along" narrative style. I do echo some of @brian-rose's concerns. I think it is dense, and spacing out with screenshots, diagrams, etc. will definitely help. I'm glad to save that for the final overarching review. I worry that some of the content that blends over into branching, remotes, forks, etc. makes it harder to get to "how to make a PR" if someone has been following the full lesson. I think on its own this is a good overview "from zero to PR" but wonder how it will fit relative to other GitHub content. I'm glad to pass this in so we can get a better idea of that, but just wanted to express my thoughts there for any further discussion! Thanks @clyne

2022-01-26 20:51 UTC, clyne commented on foundations/github/github-pull-request.md
> +| [Issues and Discussions](https://foundations.projectpythia.org/foundations/github/github-issues.html)       | Recommended |       |
Done.

2022-01-26 20:53 UTC, clyne commented on foundations/github/github-pull-request.md
> +```
Agreed. There is a lot of overlap between the second half of the branches section, and this PR. We'll need to figure out the best way to present the material.

2022-01-26 20:57 UTC, clyne commented
> So I've reviewed so far basically just for small things. Looks great, and I **really** appreciate the introductory section and the "code along" narrative style. I do echo some of @brian-rose's concerns. I think it is dense, and spacing out with screenshots, diagrams, etc. will definitely help. I'm glad to save that for the final overarching review. I worry that some of the content that blends over into branching, remotes, forks, etc. makes it harder to get to "how to make a PR" if someone has been following the full lesson. I think on its own this is a good overview "from zero to PR" but wonder how it will fit relative to other GitHub content. I'm glad to pass this in so we can get a better idea of that, but just wanted to express my thoughts there for any further discussion! Thanks @clyne

Agreed. All good points. @jukent did a great job of including screenshots in #207. We need to figure out how to best organize all of the content, but I think we do that as a separate pass and look at the entire Intro to GitHub section.

2022-01-26 21:00 UTC, dcamron approved these changes
Unrelated link failures aside, let's get this in. Thanks again @clyne

2022-01-26 23:50 UTC, clyne commented
Awesome. Thanks! Merging

2022-01-26 23:51 UTC, merged