Matplotlib
ProjectPythia/pythia-foundations pull request #230
Opened 2022-02-18 23:28 UTC by jukent

Attempt to resolve #167

2022-02-18 23:28 UTC, jukent commented
I've addressed @michaelavs and @brian-rose 's comments

2022-02-21 03:28 UTC, mgrover1 commented on core/matplotlib/additional-topics2.ipynb
> +{
<p>The verbs here should be consistent - consider changing "Learn" in the first two bullets to "Learning"</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ProjectPythia/pythia-foundations/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-02-21 03:28 UTC, mgrover1 commented on core/matplotlib/additional-topics2.ipynb
> +{
<p>Maybe add a small snippet here providing an overview of what a colormap is</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ProjectPythia/pythia-foundations/pull/230/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2022-02-21 03:29 UTC, mgrover1 requested changes
Looks great - thanks for making those changes! Just a couple of minor comments, also for some reason the Pandas notebook was changed too, with the small change being that your branch uses `master` instead `main` for the branch... not sure why that change is tracked here...

2022-02-21 17:26 UTC, brian-rose reviewed
I resolved several comment threads, and opened a few new ones over at ReviewNB. I'm not sure why my comments are showing up here on GitHub. I had the same problem in #170. But my comments should be visible on ReviewNB.

2022-02-22 17:45 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +{
<p>I changed all these bullets to match the section headings.</p>

2022-02-22 19:54 UTC, mgrover1 approved these changes
Looks great @jukent - thanks for making those changes!

2022-02-22 20:46 UTC, brian-rose commented
@jukent there seem to be new changes in this PR and also in #170 that have diverged from each other. E.g. I can't see the dropdown menus for the colormaps in this version. Can you attempt to get all the changed merged into this PR?

2022-02-22 20:59 UTC, jukent commented
> Looks great - thanks for making those changes! Just a couple of minor comments, also for some reason the Pandas notebook was changed too, with the small change being that your branch uses `master` instead `main` for the branch... not sure why that change is tracked here...

This PR kept failing because of a link in the pandas notebook being broken. I should have made that change in a separate PR, but I just quickly did it here.

2022-02-22 21:14 UTC, jukent commented
@brian-rose Thanks for catching that, it should be updated now.

2022-02-22 22:04 UTC, brian-rose reviewed
I tried to fix one link and noted a small formatting issue. Everything else looks great!

2022-02-22 22:04 UTC, brian-rose commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
I love these dropdowns! A huge improvement to the readability of this section. Nice work.

There are a couple of formatting issues with the enumerated list of dropdowns:
1. The numbers are all showing up as "1"
2. The titles should be in bold but they're not showing up that way in the preview. Instead there are written literally, like `**Sequential:**`.  The formatting may work if you move the colon outside of the `**` block. I put suggestions below.

2022-02-22 22:18 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
Thank you! The formatting was bothering me. Now in reviewNB the "summary" text is not displaying. Only the word "details"

2022-02-22 22:28 UTC, brian-rose commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
On the latest preview, the numbering looks good but the bold font is still not showing up. 

(I'm not using reviewNB anymore here, just focussing on the rendered preview on netlify since that's an accurate depiction of what it will look like after merging the PR)

2022-02-22 22:28 UTC, brian-rose commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
I'll grab a copy of your branch and see if I can figure out the bold font formatting.

2022-02-22 22:32 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
I'm not sure if the numbers are necessary. I tried using `<b></b>` as well, it seems that html doesn't obey the boldness within a dropdown.

2022-02-22 22:32 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
https://stackoverflow.com/questions/4951623/partially-bold-text-in-an-html-select

2022-02-22 22:33 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
I'm thinking of just deleting the attempt at bolding.

2022-02-22 22:37 UTC, brian-rose commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
> I'm thinking of just deleting the attempt at bolding.

That's definitely an option, but I just tried using `<b> </b>` and it seemed to work fine. Want me to push that change here?

2022-02-22 22:51 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
That'd be great!

2022-02-22 23:18 UTC, brian-rose commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
Done.

2022-02-22 23:51 UTC, jukent commented on core/matplotlib/additional-topics2.ipynb
> +    "Click the dropdown arrow to see examples of colormaps within their respective classes.\n",
Ready for merge?

2022-02-23 00:04 UTC, merged