Add overview of geoscience stack
ProjectPythia/pythia-foundations pull request #265
Opened 2022-04-18 01:30 UTC by DamienIrving

I've had a go at expanding the [overview](https://foundations.projectpythia.org/core/overview.html) of the Python geoscience software stack.

The content I've added has been adapted from [this page](https://pyaos.github.io/stack/) on the PyAOS website. Incorporating some of the PyAOS content into Pythia Foundations is something we've been [discussing](https://github.com/ProjectPythia/projectpythia.github.io/discussions/210) for a while.

2022-04-18 14:34 UTC, brian-rose reviewed
Hi @DamienIrving, thanks for getting this started!

I just went through quickly and added several suggested edits to use consistent capitalization of library names.

I think this is a really nice starting point for our presentation of the stack.

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +the [SciPy](https://www.scipy.org/scipylib/index.html) library is the default.
```suggestion
the [SciPy](https://scipy.org) library is the default.
```

To fix the broken link!

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +the default library is [matplotlib](https://matplotlib.org/).
```suggestion
the default library is [Matplotlib](https://matplotlib.org/).
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +As you can see at the [matplotlib gallery](https://matplotlib.org/stable/gallery/index.html),
```suggestion
As you can see at the [Matplotlib gallery](https://matplotlib.org/stable/gallery/index.html),
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +The [cartopy](https://scitools.org.uk/cartopy/docs/latest/) library
```suggestion
The [Cartopy](https://scitools.org.uk/cartopy/docs/latest/) library
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +The most popular high-level data science library is undoubtedly [pandas](http://pandas.pydata.org/).
```suggestion
The most popular high-level data science library is undoubtedly [Pandas](http://pandas.pydata.org/).
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +The key advance offered by pandas is the concept of labelled arrays.
```suggestion
The key advance offered by Pandas is the concept of labelled arrays.
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +traditionally performed with SciPy, datetime and matplotlib,
```suggestion
traditionally performed with SciPy, datetime and Matplotlib,
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +One of the limitations of pandas
```suggestion
One of the limitations of Pandas
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +The [xarray](http://xarray.pydata.org/) library was therefore created
```suggestion
The [Xarray](http://xarray.pydata.org/) library was therefore created
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +Not all of the pandas functionality is available
```suggestion
Not all of the Pandas functionality is available
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +makes the xarray data array far easier to deal with than the NumPy array.
```suggestion
makes the Xarray data array far easier to deal with than the NumPy array.
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +xarray also has built in functionality for reading/writing specific geoscience file formats
```suggestion
Xarray also has built in functionality for reading/writing specific geoscience file formats
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +(e.g. you might create a plot with xarray and then call a specific matplotlib
```suggestion
(e.g. you might create a plot with Xarray and then call a specific Matplotlib
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +to check whether a high-level library like pandas or xarray has the functionality you need.
```suggestion
to check whether a high-level library like Pandas or Xarray has the functionality you need.
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +only to find that xarray automatically keeps this information upon reading a netCDF file.
```suggestion
only to find that Xarray automatically keeps this information upon reading a netCDF file.
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +(e.g. the MetOffice supports cartopy)
```suggestion
(e.g. the MetOffice supports Cartopy)
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +or the wider PyData community (e.g. NumPy, pandas, xarray).
```suggestion
or the wider PyData community (e.g. NumPy, Pandas, Xarray).
```

2022-04-18 14:34 UTC, brian-rose commented on core/overview.md
> +(which are able to handle data arrays from NumPy or xarray).
```suggestion
(which are able to handle data arrays from NumPy or Xarray).
```

2022-04-18 14:43 UTC, mgrover1 requested changes
Thanks for taking the time to put together this fantastic overview @DamienIrving - just a couple of minor comments. This will be a great addition to the Foundations content 😁

2022-04-18 14:43 UTC, mgrover1 commented on core/overview.md
> +NumPy also includes a `datetime64` module for efficient vectorized datetime operations
Can you add a link to the date time module in numpy?

2022-04-18 14:43 UTC, mgrover1 commented on core/overview.md
> +The key advance offered by pandas is the concept of labelled arrays.
Also, labelled --> labeled

2022-04-18 21:19 UTC, DamienIrving commented on core/overview.md
> +NumPy also includes a `datetime64` module for efficient vectorized datetime operations
Addressed in https://github.com/ProjectPythia/pythia-foundations/pull/265/commits/738a3e0d816d3a0a65e564cb3f14193007c91284

2022-04-18 21:19 UTC, DamienIrving commented on core/overview.md
> +The key advance offered by pandas is the concept of labelled arrays.
> Also, labelled --> labeled

Addressed in https://github.com/ProjectPythia/pythia-foundations/pull/265/commits/738a3e0d816d3a0a65e564cb3f14193007c91284

2022-04-18 21:20 UTC, DamienIrving commented
Thanks, @brian-rose and @mgrover1. I've gone ahead and made all the changes you suggested.

2022-04-18 22:25 UTC, mgrover1 approved these changes
Thanks for making those changes @DamienIrving !

2022-04-19 16:35 UTC, brian-rose reviewed
Sorry just one more suggestion, with an explicit link to the Pythia Resource Gallery. Otherwise good to go!

2022-04-19 16:35 UTC, brian-rose commented on core/overview.md
> +
```suggestion
Also check out the [Pythia Resource Gallery](https://projectpythia.org/gallery.html) and try filtering by domain.

```

2022-04-20 06:16 UTC, DamienIrving commented
Done :-)

2022-04-20 13:10 UTC, merged