Clarifying how shared colorbars are created
ProjectPythia/pythia-foundations pull request #310
Opened 2022-07-12 16:46 UTC by hCraker

This PR closes #276 

During the recent Pythia Hacakthon, I made a [cookbook](https://github.com/ProjectPythiaCookbooks/mpl-colorbar-cookbook) explaining how to make shared colorbars in matplotlib and how to choose accessible colormaps. It was determined in the linked issue that the information in the cookbook is better suited for pythia-foundations. This PR adds information that was in the cookbook to the relevant existing sections of pythia-foundations.

2022-07-13 17:13 UTC, r-ford commented on core/matplotlib/annotations-colorbars-layouts.ipynb
>     "id": "1662bf3c",
<blockquote>Thus, it does matter in this particular example which output from <code>contourf</code> is used to make the colorbar.</blockquote><p>I think an emphasis on <em>does </em>would help, since I read it as "doesn't" at first.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ProjectPythia/pythia-foundations/pull/310/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2022-07-13 17:13 UTC, r-ford commented on core/matplotlib/annotations-colorbars-layouts.ipynb
>     "id": "1662bf3c",
<blockquote>In fact, we used this when ploting the histograms just above!</blockquote><p>Is this section meant to go after the two plots below? I think it would flow better that way.</p><p> </p><p>Also "ploting" --&gt; "plotting"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ProjectPythia/pythia-foundations/pull/310/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='35'/>

2022-07-15 18:22 UTC, r-ford approved these changes
Looks good!

2022-07-21 18:06 UTC, mgrover1 commented on core/matplotlib/annotations-colorbars-layouts.ipynb
>     "id": "1662bf3c",
<p>Agree with previous comment - maybe reword to "This functionality was utilized with the previous histogram exercise"?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/ProjectPythia/pythia-foundations/pull/310/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='38'/>

2022-07-21 18:06 UTC, mgrover1 requested changes
One small suggestion - other than that, it looks great! Thanks @hCraker

2022-07-22 16:06 UTC, mgrover1 approved these changes
Great! Thanks @h

2022-07-25 14:18 UTC, merged