Content on how to Review a PR
ProjectPythia/pythia-foundations pull request #316
Opened 2022-08-22 18:09 UTC by jukent

I hope it isn't too meta to review this PR on reviewing a PR

2022-09-07 15:45 UTC, dcamron requested changes
Good pacing, short and sweet, hits the highlights, and good use of screenshots. Now that I'm _doing_ a review, the only other thing that might be worth adding is a concrete explanation of the final "finish your review" dialog and the difference between Comment, Approve, and Request Changes.

Oh, and the new file hasn't been added to the TOC yet, so you can only get to it from the links you added!

2022-09-07 15:45 UTC, dcamron commented on foundations/github/review-pr.md
> +- And voice the limitations of your review! It is okay to not address all of these points in your review, but let your team know what you did look for (content vs code, e.g.). Your opinion matters.
I _really_ love seeing "Your opinion matters." here. Personally I'd even want to elevate this or otherwise begin/end this section with an emphasis on that addressing the "fear to review". Something something "hey, people want to make the best project they can and want your feedback to get there, so dive in!"

2022-09-07 21:41 UTC, jukent commented
Thanks for your review @dcamron Getting to these points now.

2022-09-07 21:44 UTC, jukent commented on foundations/github/review-pr.md
> +- And voice the limitations of your review! It is okay to not address all of these points in your review, but let your team know what you did look for (content vs code, e.g.). Your opinion matters.
Great ideas @dcamron !

2022-09-07 22:14 UTC, jukent commented on foundations/github/review-pr.md
> +This method is generally preferred if you have small edits that are easy for you, the reviewer, to implement yourself.
I've added it to the TOC, highlighted the suggestion button, ran down the different comment/approve/request  options and added a line abut finishing your review. Thanks @dcamron let me know if anything is still lacking.

2022-09-12 17:28 UTC, ktyle requested changes
Looking good @jukent!

Regarding review_pr.md:

Line 42: reword 
``` 
enter and request from the GitHub user's
``` 
to

```
select or enter a GitHub user's ID
```

Line 60: suggest adding a link to [GitHub Actions](https://docs.github.com/en/actions)

Line 62: eliminate first comma

Line 64: Wether --> Whether

Line 105: contributor's --> contributors

Line 106: change comma to semicolon

2022-09-12 17:46 UTC, jukent commented
Thanks @ktyle 
Just addressed these typos and improvements.

2022-09-15 15:26 UTC, ktyle approved these changes
Nice work @jukent ! I think this is good to go!

2022-09-19 16:19 UTC, jukent commented
@dcamron will you take one last look at this before we merge!

2022-09-19 16:26 UTC, dcamron commented
> @dcamron will you take one last look at this before we merge!

Yep, though it might be mid-afternoon today before so. Thanks for the nudge!

2022-09-21 16:13 UTC, dcamron approved these changes

2022-09-21 16:13 UTC, merged