Clarify Array Slicing Syntax from 'array[start:stop[:step]]' to 'array[start:stop:step]'
ProjectPythia/pythia-foundations pull request #465
Opened 2024-04-26 13:53 UTC by kazakhpunk

This pull request updates the array slicing syntax documentation. The original syntax notation 'array[start:stop[:step]]' could be misinterpreted as suggesting the step parameter is nested within the stop parameter. This update simplifies the notation to 'array[start:stop:step]', clearly delineating each parameter, enhancing readability and reducing potential confusion for users.

2024-04-26 20:03 UTC, dopplershift commented
The challenge with this update is now it implies that the second colon is mandatory, which isn't true. That's why `:step` was in its own brackets before.

In fairness, neither the [numpy docs](https://numpy.org/doc/1.26/user/basics.indexing.html#slicing-and-striding) nor the [Python docs](https://docs.python.org/3/reference/datamodel.html#sequences) denote slicing as we have previously done here, so maybe this is a good cleanup to match those sources.

2024-04-28 14:02 UTC, kazakhpunk commented
Thank you for the feedback. I appreciate the concern about the notation implying that the second colon and the step parameter are mandatory. 

I propose we adopt 'array[start:stop:step]' as the primary notation in examples but include a clear note in the text explaining that the step parameter is optional: "The step parameter is optional and can be omitted, in which case the slice uses a default step of 1."

2024-05-01 13:41 UTC, jukent submitted a review, later dismissed
Thanks for this clarification!

2024-05-08 02:11 UTC, brian-rose requested changes

2024-05-08 02:11 UTC, brian-rose commented on core/numpy/numpy-basics.ipynb
> +    "Slicing syntax is written as `array[start:stop:step]'. Note that **all numbers are optional**. Importantly, the **step** parameter is optional and can be omitted, in which case the slice uses a
I think there's a little syntax error here preventing the text from rendering properly.

It should be `array[start:stop:step]` (closed with the back quote) instead of `array[start:stop:step]'

2024-05-08 06:04 UTC, kazakhpunk commented
Thank you for this feedback!

I've changed `array[start:stop:step]' to `array[start:stop:step]`

2024-05-08 14:08 UTC, brian-rose approved these changes
Thanks for that fix @kazakhpunk, this looks good now!

The link check failure is unrelated to this PR.

2024-05-20 18:24 UTC, brian-rose commented
Merging this now. Thanks for the contribution @kazakhpunk!

2024-05-20 18:24 UTC, merged